name: "Lint"
on:
  pull_request:
    types: [ opened, synchronize ]
    paths-ignore:
      - '*.md'
    branches:
      - master

  workflow_dispatch:

jobs:
  lint:
    name: "Run linter"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Go Lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          cache: true

      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"