name: Test code

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
  pull_request:
    types: [ opened, synchronize ]
    paths-ignore:
      - '*.md'
    branches:
      - master

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17"

      - name: Install deps & build
        run: |
          go mod download
          go build -v ./...

      - name: Test with the Go CLI
        run: go test
